services:
  - type: web
    name: barakatoping-backend
    env: python
    plan: free
    buildCommand: pip install -r backend/requirements.txt
    startCommand: python -m backend.src.main
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: baraka-db
          property: connectionString
      - key: PYTHONUNBUFFERED
        value: "true"
      - fromGroup: baraka-secrets

  - type: web
    name: barakatoping-frontend
    env: static
    plan: free
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/dist
    headers:
      - path: /*
        name: ngrok-skip-browser-warning
        value: "true"

databases:
  - name: baraka-db
    plan: free
    region: frankfurt
